import { index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

import { user } from '@/db/schema/auth';
import { activityTypeEnum } from '@/db/schema/enums';
import { projects } from '@/db/schema/projects';
import { tasks } from '@/db/schema/tasks';
import { tickets } from '@/db/schema/tickets';

export const activityLog = pgTable(
  'activity_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    ticketId: uuid('ticket_id').references(() => tickets.id, { onDelete: 'set null' }),
    taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'set null' }),
    // Null means the entry was generated by the system rather than a user action.
    actorId: uuid('actor_id').references(() => user.id, { onDelete: 'set null' }),
    type: activityTypeEnum('type').notNull(),
    description: text('description').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('activity_log_project_id_idx').on(table.projectId),
    index('activity_log_ticket_id_idx').on(table.ticketId),
    index('activity_log_task_id_idx').on(table.taskId),
    index('activity_log_actor_id_idx').on(table.actorId),
    index('activity_log_created_at_idx').on(table.createdAt),
  ],
);
