import { Client } from "@/models/client";
import { ProjectStatus } from "@/models/enums/project-status";
import { NavItem } from "@/models/nav-item";
import { Project } from "@/models/project";
import { LayoutDashboard, PanelsTopLeft, SquareUser } from "lucide-react";
import { v4 as uuidv4 } from "uuid";

export const navItems: NavItem[] = [
  {
    icon: LayoutDashboard,
    title: "Dashboard",
    route: "/",
    variant: "default",
  },
  {
    icon: SquareUser,
    title: "Clients",
    route: "/clients",
    variant: "default",
  },
  {
    icon: PanelsTopLeft,
    title: "Projects",
    route: "/projects",
    variant: "default",
  },
];

export const projectsTabelHeaders: { key: keyof Project; label: string }[] = [
  { key: "title", label: "Title" },
  { key: "clientId", label: "Client" },
  { key: "createdOn", label: "Started on" },
  { key: "updatedOn", label: "Updated on" },
  { key: "status", label: "Status" },
];

export const clientsTableHeaders: { key: keyof Client; label: string }[] = [
  { key: "name", label: "Client" },
  { key: "email", label: "Name" },
  { key: "phone", label: "Phone" },
  { key: "address", label: "Address" },
  { key: "vatNumber", label: "VAT" },
  { key: "balance", label: "Balance" },
  { key: "createdOn", label: "Client since" },
];

export const projectsMockingData: Project[] = [
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.NotStarted,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.Planning,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.Designing,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.InDevelopment,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.InTest,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
  {
    id: uuidv4(),
    title: "Dashboard for clients",
    clientId: uuidv4(),
    designUri: "",
    testUri: "",
    productionUri: "",
    backofficeUri: "",
    vercelUri: "",
    status: ProjectStatus.Deployed,
    repositoryUri: "",
    createdBy: "Eloy Boone",
    createdOn: new Date(),
  },
];

export const clientsMockingData: Client[] = [
  {
    id: "001",
    name: "Tech Innovators Inc.",
    email: "contact@techinnovators.com",
    phone: "+1-555-123-4567",
    address: "123 Innovation Drive, San Francisco, CA, USA",
    vatNumber: "US123456789",
    logoUri: "https://example.com/logos/techinnovators.png",
    language: "en",
    balance: 15345.25,
    createdOn: new Date(),
    createdBy: "Eloy Boone",
  },
  {
    id: "002",
    name: "Creative Solutions Ltd.",
    email: "info@creativesolutions.com",
    phone: "+44-20-9876-5432",
    address: "456 Design Street, London, UK",
    vatNumber: "GB987654321",
    logoUri: "https://example.com/logos/creativesolutions.png",
    language: "en",
    balance: 20455.75,
    createdOn: new Date(),
    createdBy: "Eloy Boone",
  },
  {
    id: "003",
    name: "Global Commerce Group",
    email: "support@globalcommerce.com",
    phone: "+34-91-234-5678",
    address: "789 Business Blvd, Madrid, Spain",
    vatNumber: "ES123456789",
    language: "es",
    balance: 9050.5,
    createdOn: new Date(),
    createdBy: "Eloy Boone",
  },
  {
    id: "004",
    name: "Innovative Technologies GmbH",
    email: "sales@innotech.de",
    phone: "+49-30-9876-5432",
    address: "321 Tech Park, Berlin, Germany",
    vatNumber: "DE987654321",
    logoUri: "https://example.com/logos/innotech.png",
    language: "de",
    balance: 15765.0,
    createdOn: new Date(),
    createdBy: "Eloy Boone",
  },
  {
    id: "005",
    name: "Asia Trading Co.",
    email: "hello@asiatrading.com",
    phone: "+86-10-1234-5678",
    address: "99 Trade Center, Beijing, China",
    vatNumber: "CN123456789",
    language: "zh",
    balance: 7850.0,
    createdOn: new Date(),
    createdBy: "Eloy Boone",
  },
];
